### ISSUE TITLE
New competitor: rechtsinfo_api

### ISSUE THREAD

**Issue by pogoba** [kmein/gesetze#5]
since august 2020 there is a project, making laws from bundesanzeiger available in machine readable form: https://github.com/tech4germany/rechtsinfo_api

this should be referenced in the readme or so.

**Comment by kmein** [comment]
Thank you! I'll mention the project in the readme of https://github.com/kmein/recht.

**Comment by kmein** [comment]
https://github.com/kmein/recht/commit/7c15b13328fb5cee01012c488ff235ee730cac70
